graph TD
    StartSession --> Greeting
    
    Greeting --> ChooseMood
    Greeting --> Settings
    Greeting --> Activity
    Greeting --> EndSession

    Activity --> ShowStats
    Settings --> On/Off_Stats
    Settings --> On/Off_History

    ShowStats --> Greeting
    On/Off_Stats --> Greeting
    On/Off_History --> Greeting

    ChooseMood ---> Happy
    ChooseMood ---> Sad
    ChooseMood ---> Angry
    ChooseMood ---> Tired
    ChooseMood ---> Calm

    Happy --> ChooseContent
    Sad --> ChooseContent
    Angry --> ChooseContent
    Tired --> ChooseContent
    Calm --> ChooseContent

    ChooseContent --> Films
    ChooseContent --> Pictures
    ChooseContent --> CatMemes

    Films --> GenerateContent
    Pictures --> GenerateContent
    CatMemes --> GenerateContent

    GenerateContent --> AskNext  

    AskNext --> ChooseContent
    AskNext --> ChooseMood
    AskNext --> Greeting
    AskNext --> EndSession
